In [1]:
import soundfile as sf
import sounddevice as sd

def test_live_audio_stream_handler():
    # handler = LiveAudioStreamHandler(Agent())
    # stream = AudioStream
    # handler.set_input_stream(None)
    data, samplerate = sf.read('jfk.flac')
    sd.play(data, samplerate)
    sd.wait()

In [8]:
file = sf.SoundFile('jfk.flac')
d1 = file.read(3)
d2 = file.read(3)
d3 = file.read(3)

In [13]:
d1

array([[-1.1920929e-07,  0.0000000e+00],
       [-1.1920929e-07,  0.0000000e+00],
       [ 0.0000000e+00,  0.0000000e+00]])

In [14]:
d2

array([[-1.1920929e-07,  0.0000000e+00],
       [-1.1920929e-07, -1.1920929e-07],
       [ 0.0000000e+00, -1.1920929e-07]])

In [12]:
import numpy as np
np.concatenate((d1, d2, d3), axis=0)

array([[-1.1920929e-07,  0.0000000e+00],
       [-1.1920929e-07,  0.0000000e+00],
       [ 0.0000000e+00,  0.0000000e+00],
       [-1.1920929e-07,  0.0000000e+00],
       [-1.1920929e-07, -1.1920929e-07],
       [ 0.0000000e+00, -1.1920929e-07],
       [ 0.0000000e+00,  0.0000000e+00],
       [-1.1920929e-07, -1.1920929e-07],
       [-1.1920929e-07, -1.1920929e-07]])

In [10]:
d2

array([[-1.1920929e-07,  0.0000000e+00],
       [-1.1920929e-07, -1.1920929e-07],
       [ 0.0000000e+00, -1.1920929e-07]])

In [9]:
d3

array([[ 0.0000000e+00,  0.0000000e+00],
       [-1.1920929e-07, -1.1920929e-07],
       [-1.1920929e-07, -1.1920929e-07]])

In [2]:
data, samplerate = sf.read('jfk.flac')

In [3]:
data.shape

(485100, 2)

In [7]:
samplerate

44100

In [9]:
data.shape[0] / samplerate

11.0

In [10]:
d2, sr2 = sf.read('jfk.flac', frames=1000)

In [11]:
d2.shape

(1000, 2)

In [12]:
sr2

44100

In [16]:
from ..src.agent import LiveAudioStreamHandler, Agent
from ..src.stream import AudioStream

ModuleNotFoundError: No module named 'src'